# Generated by Django 4.0.1 on 2022-02-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=2)),
                ('purpose', models.CharField(max_length=100)),
                ('reference', models.TextField(blank=True)),
                ('departure', models.CharField(max_length=255)),
                ('arrival', models.CharField(max_length=255)),
                ('stopover', models.TextField(blank=True)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('is_driver', models.BooleanField(default=False)),
                ('total_number', models.CharField(max_length=10)),
                ('convenience', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('bus_cnt', models.CharField(blank=True, max_length=5)),
                ('bus_type', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'kingbus_dispatch_order',
            },
        ),
        migrations.CreateModel(
            name='Regularly_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=1)),
                ('term_begin', models.DateField()),
                ('term_end', models.DateField()),
            ],
            options={
                'db_table': 'kingbus_regulary_order',
            },
        ),
        migrations.CreateModel(
            name='Dispatch_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=10)),
                ('bus_cnt', models.CharField(blank=True, max_length=5)),
                ('bus_type', models.CharField(blank=True, max_length=64)),
                ('is_toll_gate', models.BooleanField(default=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('is_accomodation', models.BooleanField(default=False)),
                ('is_meal', models.BooleanField(default=False)),
                ('is_convenience', models.BooleanField(default=False)),
                ('driverorcompany', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatch_order')),
            ],
            options={
                'db_table': 'kingbus_estimate',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dispatch.dispatch_order')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('estimate_confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('estimate_order_time', models.DateTimeField(blank=True, null=True)),
                ('reservation_confirmed', models.BooleanField(default=False)),
                ('regularly', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.regularly_order')),
                ('selected_estimate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatch_estimate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kingbus_dispatch',
            },
        ),
    ]
