# Generated by Django 4.0.1 on 2022-03-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='driver_schedule',
            field=models.TextField(blank=True),
        ),
    ]
