# Generated by Django 4.0.1 on 2022-02-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='dispatch',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='dispatch_order',
            name='bus_cnt',
        ),
        migrations.RemoveField(
            model_name='dispatch_order',
            name='bus_type',
        ),
        migrations.RemoveField(
            model_name='dispatch_order',
            name='price',
        ),
    ]
