# Generated by Django 4.0.1 on 2022-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatchorder_driver_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchestimate',
            name='pricebycar',
            field=models.CharField(default='123123', max_length=10),
            preserve_default=False,
        ),
    ]
