# Generated by Django 4.0.1 on 2022-02-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0002_rename_dispatch_dispatch_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_estimate',
            name='driverorcompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
