# Generated by Django 4.0.1 on 2022-03-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_dispatchorder_total_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='total_distance',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
