# Generated by Django 4.0.1 on 2022-03-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_rename_arrival_dispatchorder_comeback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchorder',
            old_name='comeback',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='dispatchorder',
            old_name='comeback_short',
            new_name='arrival_short',
        ),
    ]
