# Generated by Django 4.0.1 on 2022-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_rename_comeback_dispatchorder_arrival_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='estimate_confirmed_time',
            new_name='confirmed_time',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='estimate_order_time',
            new_name='estimate_time',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='selected_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='reservation_confirmed',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
