# Generated by Django 4.0.1 on 2022-03-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_rename_estimate_confirmed_time_dispatch_confirmed_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='reservation_confirmed',
            new_name='dispatch_status',
        ),
    ]
