# Generated by Django 4.0.1 on 2022-03-02 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like_cnt', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kingbus_community_comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('kinds', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('like_cnt', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kingbus_community_post',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('blocked_profile', models.ManyToManyField(to='community.Profile')),
                ('liked_comment', models.ManyToManyField(related_name='liked_comment', to='community.Comment')),
                ('liked_post', models.ManyToManyField(related_name='liked_post', to='community.Post')),
            ],
            options={
                'db_table': 'kingbus_community_profile',
            },
        ),
        migrations.CreateModel(
            name='Recomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomment', models.TextField()),
                ('like_cnt', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.profile')),
            ],
            options={
                'db_table': 'kingbus_comminity_recomment',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_recomment',
            field=models.ManyToManyField(related_name='liked_recomment', to='community.Recomment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='scrap',
            field=models.ManyToManyField(related_name='scrap', to='community.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.profile'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post')),
            ],
            options={
                'db_table': 'kingbus_community_photo',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.profile'),
        ),
    ]
