# Generated by Django 4.0.1 on 2022-03-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked_profile',
            field=models.ManyToManyField(blank=True, to='community.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_comment',
            field=models.ManyToManyField(blank=True, related_name='liked_comment', to='community.Comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_post',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to='community.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_recomment',
            field=models.ManyToManyField(blank=True, related_name='liked_recomment', to='community.Recomment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='scrap', to='community.Post'),
        ),
    ]
