# Generated by Django 4.0.1 on 2022-03-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_profile_blocked_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Image',
        ),
    ]
