# Generated by Django 4.0.1 on 2022-03-03 05:34

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_rename_photo_image_image_alter_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=community.models.Image.upload_to_func),
        ),
    ]
