# Generated by Django 4.0.1 on 2022-03-07 02:42

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=community.models.Image.upload_to_func),
        ),
    ]
