# Generated by Django 4.0.1 on 2022-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
