# Generated by Django 4.0.1 on 2022-03-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_recomment_like_cnt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recomment',
            table='kingbus_community_recomment',
        ),
    ]
