# Generated by Django 4.0.1 on 2022-01-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyacc',
            name='company_business_registration',
            field=models.ImageField(default=1, upload_to='company_businessregistration<function CompanyAcc.upload_to_func at 0x7f070a51e280>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_com_name',
            field=models.CharField(default='sss', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_companylocation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_introduction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='company_introduction_video<function CompanyAcc.upload_to_func at 0x7f070a51e280>'),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_tradeunion_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_tradeunion_certificate<function CompanyAcc.upload_to_func at 0x7f070a51e280>'),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_transportationbusiness_registration',
            field=models.ImageField(default=1, upload_to='company_transportationbusiness_registration<function CompanyAcc.upload_to_func at 0x7f070a51e280>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyacc',
            name='company_profile_vehiclecount',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_car_driverlisence',
            field=models.ImageField(default=1, upload_to='driver_driverlicenses<function DriverAcc.upload_to_func at 0x7f070a533160>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_car_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_car_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_car_option',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_carphoto<function DriverAcc.upload_to_func at 0x7f070a533160>'),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_car_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_com_name',
            field=models.CharField(default='aaa', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_profile_introduction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_profile_introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='driver_introduction_video<function DriverAcc.upload_to_func at 0x7f070a533160>'),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_profile_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='driveracc',
            name='driver_profile_tradeunion_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='driver_tradeunion_certificate<function DriverAcc.upload_to_func at 0x7f070a533160>'),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='num',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='num',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='num',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterModelTable(
            name='companyacc',
            table='kingbus_companyacc',
        ),
        migrations.AlterModelTable(
            name='driveracc',
            table='kingbus_driveracc',
        ),
        migrations.AlterModelTable(
            name='user',
            table='kingbus_user',
        ),
    ]
