# Generated by Django 4.0.1 on 2022-01-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_companyacc_company_business_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyacc',
            name='company_business_registration',
            field=models.ImageField(upload_to='company_businessregistration<function CompanyAcc.upload_to_func at 0x7fc804cda280>'),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='company_introduction_video<function CompanyAcc.upload_to_func at 0x7fc804cda280>'),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_tradeunion_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_tradeunion_certificate<function CompanyAcc.upload_to_func at 0x7fc804cda280>'),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_transportationbusiness_registration',
            field=models.ImageField(upload_to='company_transportationbusiness_registration<function CompanyAcc.upload_to_func at 0x7fc804cda280>'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_car_driverlisence',
            field=models.ImageField(upload_to='driver_driverlicenses<function DriverAcc.upload_to_func at 0x7fc804cef160>'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_carphoto<function DriverAcc.upload_to_func at 0x7fc804cef160>'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_profile_introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='driver_introduction_video<function DriverAcc.upload_to_func at 0x7fc804cef160>'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_profile_tradeunion_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='driver_tradeunion_certificate<function DriverAcc.upload_to_func at 0x7fc804cef160>'),
        ),
    ]
