# Generated by Django 4.0.1 on 2022-01-25 06:48

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_companyacc_company_business_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyacc',
            name='company_business_registration',
            field=models.ImageField(upload_to=user.models.upload_to_func_common),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_introduction_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_tradeunion_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_tradeunion_certificate/'),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_transportationbusiness_registration',
            field=models.ImageField(blank=True, null=True, upload_to='company_transportationbusiness_registration/'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_car_driverlisence',
            field=models.ImageField(upload_to=user.models.upload_to_func_common),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_carphoto/'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_profile_introduction_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_profile_tradeunion_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='driver_tradeunion_certificate/'),
        ),
    ]
