# Generated by Django 4.0.1 on 2022-04-08 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_kingbusreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingbusreview',
            name='driverorcompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_driverorcompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
