# Generated by Django 4.0.1 on 2022-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_companyacc_company_business_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyacc',
            name='company_profile_tradeunion_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_profile_tradeunion_certificate/'),
        ),
        migrations.AlterField(
            model_name='driveracc',
            name='driver_profile_tradeunion_certificate',
            field=models.FileField(blank=True, null=True, upload_to='driver_tradeunion_certificate/'),
        ),
    ]
