# Generated by Django 4.0.1 on 2022-03-30 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatroomlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomlist',
            name='driverorcompany',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='driverorcompany', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroomlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
